FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY csharp_remediator/ .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "csharp_remediator.dll"]